name: The Scary Guy
favicon: null
layout_spectrum: 0.63277
typography_spectrum: 0.66634
title: The New Face Of Love
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#353439'
    - '#b8afa6'
    - '#a92135'
  brandStrength: 0.987814394524321
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 1
purpose: []
