name: The Scary Guy
favicon: null
layout_spectrum: 0.63277
typography_spectrum: 0.66634
title: The New Face Of Love
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#6b0005'
    - '#32312d'
    - '#feaf3e'
    - '#f74a22'
  brandStrength: 0.987814394524321
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
