typography_spectrum: 0.66634
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#dab8b9'
    - '#f50000'
    - '#fe00fd'
  brandStrength: 0.987814394524321
  lightness: 0.3125
  saturation: 0
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.63277
analytics:
  google: null
  facebook: null
  twitter: null
name: The Scary Guy
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: The New Face Of Love
description: Agent For Change
purpose: []
